'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RtfControlADV.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property arrow_in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_in_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_in_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_out__16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_out__16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property closeButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disk_multiple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk_multiple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EDIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FIND() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FIND", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property font() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property highlighter_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("highlighter_color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5329114650796786863372272.
        '''</summary>
        Friend ReadOnly Property licNumber() As String
            Get
                Return ResourceManager.GetString("licNumber", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property NEWDOC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NEWDOC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pegar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pegar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrintPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_center() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_align_center", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_justify() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_align_justify", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_align_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_align_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_bold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_bold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_italic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_italic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_list_bullets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_list_bullets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_list_numbers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_list_numbers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_replace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_replace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_strikethrough() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_strikethrough", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_subscript() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_subscript", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_superscript() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_superscript", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_underline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_underline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property word() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
